// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenOr-1]
	_ = x[TokenAnd-2]
	_ = x[TokenFn-3]
	_ = x[TokenEnd-4]
	_ = x[TokenFor-5]
	_ = x[TokenWhile-6]
	_ = x[TokenIn-7]
	_ = x[TokenDo-8]
	_ = x[TokenIf-9]
	_ = x[TokenNil-10]
	_ = x[TokenBoolean-11]
	_ = x[TokenString-12]
	_ = x[TokenNumber-13]
	_ = x[TokenIdent-14]
	_ = x[TokenComma-15]
	_ = x[TokenSemicolon-16]
	_ = x[TokenSeparator-17]
	_ = x[TokenLParen-18]
	_ = x[TokenRParen-19]
	_ = x[TokenLBrace-20]
	_ = x[TokenRBrace-21]
	_ = x[TokenLBracket-22]
	_ = x[TokenRBracket-23]
	_ = x[TokenBang-24]
	_ = x[TokenDot-25]
	_ = x[TokenPlus-26]
	_ = x[TokenMinus-27]
	_ = x[TokenMul-28]
	_ = x[TokenDiv-29]
	_ = x[TokenSet-30]
	_ = x[TokenEq-31]
	_ = x[TokenNeq-32]
	_ = x[TokenLt-33]
	_ = x[TokenGt-34]
	_ = x[TokenLeq-35]
	_ = x[TokenGeq-36]
}

const _TokenType_name = "TokenEOFTokenOrTokenAndTokenFnTokenEndTokenForTokenWhileTokenInTokenDoTokenIfTokenNilTokenBooleanTokenStringTokenNumberTokenIdentTokenCommaTokenSemicolonTokenSeparatorTokenLParenTokenRParenTokenLBraceTokenRBraceTokenLBracketTokenRBracketTokenBangTokenDotTokenPlusTokenMinusTokenMulTokenDivTokenSetTokenEqTokenNeqTokenLtTokenGtTokenLeqTokenGeq"

var _TokenType_index = [...]uint16{0, 8, 15, 23, 30, 38, 46, 56, 63, 70, 77, 85, 97, 108, 119, 129, 139, 153, 167, 178, 189, 200, 211, 224, 237, 246, 254, 263, 273, 281, 289, 297, 304, 312, 319, 326, 334, 342}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
